### ISSUE TITLE
Text issue on split card at md query

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#10]
At the `md` query, the text on the split card gets half hidden. We should probably define when to trim it.  
![trim](https://cloud.githubusercontent.com/assets/19909772/18432334/b70537ba-78e1-11e6-86a0-ed269492fb9e.PNG)

**Comment by matthewmorek** [comment]
I'll work on typography scale in this viewport, to make sure we've got it all displaying properly.
