### ISSUE TITLE
No opacity background at sm and xs media queries

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#11]
I've noticed there's no opacity background at smaller breakpoints. The background image of stories text is gray, no transparency. Was this requested?
![no opacity background](https://cloud.githubusercontent.com/assets/19909772/18436360/3eabd87a-78f8-11e6-91e5-823889d670ff.PNG)

**Comment by matthewmorek** [comment]
This might be the side-effect of how image and content are stacked at the smallest viewport sizes we cannot overlay the text on top of the image, as the image will be mostly covered by it.

I can increase contrast of the text background, so it's displayed appropriately, or I could match the look of other card types for this viewport only.
