### ISSUE TITLE
cards: different length

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#12]
As I guess the div adapts to text's length, the grid at sm and smaller queries doesn't remain aligned. We should discuss whether is more convenient to trim text or have fix height for those cards. Any ideas?
 
![cards different lenght](https://cloud.githubusercontent.com/assets/19909772/18436778/52e48646-78fa-11e6-8dc4-50e72fd52569.PNG)

**Comment by jrah** [comment]
I think this might have been caused by my fix for #9.

**Comment by matthewmorek** [comment]
@danielapizzurro These should have a dynamic height that matches one another. I'll investigate.
