### ISSUE TITLE
Download policy button

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#3]
Might be because we've introduced the show more element, which has broken the previous layout, but the "download policy" button seems to be floating. Maybe we could try find a better way of placing the button in way that seems more logic.
![download button](https://cloud.githubusercontent.com/assets/19909772/17856416/c041f5da-687d-11e6-82f0-6fea2655344b.PNG)

**Comment by matthewmorek** [comment]
@danielapizzurro Do you have any ideas that might suit this section?

**Comment by danielapizzurro** [comment]
I was thinking at the sidebar that shows the data; we could place the button in that area, right below. Do you have any other ideas? Anyways, before we make the changes to the HTML maybe you could make a quick/low fidelity screenshot, so that we can see and decide.

**Comment by jrah** [comment]
How I interpreted @danielapizzurro suggestion:
<img width="1061" alt="screenshot 2016-08-30 15 51 22" src="https://cloud.githubusercontent.com/assets/1245961/18093999/d7ea046e-6ec9-11e6-8c17-2eb716809e17.png">

We could also centre the button (which might make it more consistent with other buttons/CTA that are centred):

<img width="1243" alt="screenshot 2016-08-30 15 51 56" src="https://cloud.githubusercontent.com/assets/1245961/18094017/f445c576-6ec9-11e6-85c6-bda0459bedb1.png">
<img width="866" alt="screenshot 2016-08-30 15 52 24" src="https://cloud.githubusercontent.com/assets/1245961/18094027/fa26bd2e-6ec9-11e6-8e41-aecc1aff055f.png">

/cc @matthewmorek

**Comment by matthewmorek** [comment]
@jrah It looks solid. Good job!
@danielapizzurro Beware that on mobile it was decided not to show the stats group.

**Comment by danielapizzurro** [comment]
@matthewmorek @jrah for the download button, I think the best solution would be the first one (screenshot 1), underneath the stats. If we go for it, please note that on mobile it remains visible.

**Comment by jrah** [comment]
<img width="1041" alt="screenshot 2016-09-06 15 41 55" src="https://cloud.githubusercontent.com/assets/1245961/18278038/7ffcd8c4-7448-11e6-8404-3416e391ea48.png">

We could put it inside the `pitch-stats` container.
