### ISSUE TITLE
(on mobile) Photo credits overlap with breadcrumbs

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#4]
Was is the rule here, if any? Are the breadcrumbs or photo credits going to disappear on mobile? If we keep both I guess they can't both be placed on top. 

![photo copyright](https://cloud.githubusercontent.com/assets/19909772/17901068/08f4c336-6962-11e6-9ecd-6dd95dfbd33f.PNG)

**Comment by matthewmorek** [comment]
My suggestion is to hide photo credits on mobile, as they are unlikely to be needed by the user. If we move photo credits to the bottom, they will overlap with the welcome section, so it's a double whammy at this point. @danielapizzurro Should I hide credits on smaller viewports?

**Comment by andrewholgate** [comment]
Yes, we should hide photo credits on smaller view ports, they take up too much real estate, detracting too much from the purpose of the imagery.
