### ISSUE TITLE
Breadcrumbs hidden by the menu (on tablet)

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#5]
On tablets, as the menu items wrap to the second row, it gets higher and hides the breadcrumbs 
![breadcrumbs hidden](https://cloud.githubusercontent.com/assets/19909772/18012212/e230d038-6bb8-11e6-904d-02fa07ecf2de.PNG)

**Comment by matthewmorek** [comment]
This has been fixed in the latest update.
