### ISSUE TITLE
statistics section hidden on mobile 

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#6]
On mobile, the statistics section is hidden. Was this a requirement or it's a bug? 
![data topic page](https://cloud.githubusercontent.com/assets/19909772/18013518/a9d10a54-6bbe-11e6-80c8-a5990e58a008.PNG)

**Comment by matthewmorek** [comment]
This was decided some time ago by Barbara, as far as I can recall. It's most definitely not a bug.

Due to various reasons we should not be showing/hiding different content depending on the viewport size. It can severely impact user experience.
