### ISSUE TITLE
Show more button

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#7]
@matthewmorek we're not completely convinced by the SHOW MORE button. Did you have any other ideas that we can discuss?

**Comment by matthewmorek** [comment]
@danielapizzurro I've updated template with the latest example of a _show more_ button. What exactly did not work in the previous one? Could you outline what were you not convinced about exactly?

**Comment by matthewmorek** [comment]
Based on our conversation in Slack, we're going to to ignore this entire section until we find a better solution. The requirements have likely changed since the first time this section was designed.

cc: @danielapizzurro
