### ISSUE TITLE
Card image (split) and (wide): size and ratio not the standard one

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-topics#8]
As far as I read on the [standards image sizes for the new WFP.ORG](https://gist.github.com/andrewholgate/68207cf11351c9e48d3ceb7872413790), the card (split) would have a squared image. Currently its not on any breakpoint.

> Card Image (Split)
> Size: 334x334
> Ratio: 1:1

![image size card split](https://cloud.githubusercontent.com/assets/19909772/18431519/7bf169ae-78dd-11e6-9e69-2b32e096d6f4.PNG)

PS: this can be extended to the Card Image (Wide) as it doesn't look to be a 16:9 image.

**Comment by matthewmorek** [comment]
The ratio of an image at any break points will never be exactly the same as the original, as its was chosen for best compatibility across break points. To have always a matching ratio, we would have to use 3-4 different images.

**Comment by danielapizzurro** [comment]
OK. Sorry, I had misunderstood the use of standard sizes and ratio. Now it's clear, thanks :) 
Before we close this issue though, can you help me understand why the `Resources` section, on desktop, has such huge images? I don't get what criteria is used (if not standard ratio & size at this point) to define those sizes; also it makes little sense to me to use a big portion of the page for the type of content considering the length of text, which will likely not be longer than that.
![resources images](https://cloud.githubusercontent.com/assets/19909772/18439833/16142476-7907-11e6-88d4-a6e37a091b8a.PNG)

**Comment by matthewmorek** [comment]
Fixed in 3b0aa6c837d65b297e48dfda67cc2422e00be6bc.
